version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: investment_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: investment_db
      MYSQL_USER: investment_user
      MYSQL_PASSWORD: investment_pass_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - investment_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: investment_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://investment_user:investment_pass_123@db:3306/investment_db
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - investment_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: investment_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - investment_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  investment_network:
    driver: bridge